(let ((s "test")
      (n 1000))
  (let loop ((i 0))
    (if (and (string=? s (let ((p (open-output-string)))
                           (call-with-port p (lambda (p) (write-string s p)))
                           (get-output-string p)))
             (< i n))
        (loop (+ i 1))
        i)))
